export enum HobbyType {
  SPORT = 'SPORT',
  TRAVEL = 'TRAVEL',
  MUSIC = 'MUSIC',
  CINEMA = 'CINEMA',
  READING = 'READING',
  COOKING = 'COOKING',
  DANCING = 'DANCING',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  GAMING = 'GAMING',
  FITNESS = 'FITNESS',
  HIKING = 'HIKING',
  TECHNOLOGY = 'TECHNOLOGY',
  ART = 'ART',
  THEATER = 'THEATER',
  VOLUNTEERING = 'VOLUNTEERING',
  YOGA = 'YOGA',
  SWIMMING = 'SWIMMING',
  RUNNING = 'RUNNING',
  CYCLING = 'CYCLING',
  BOARD_GAMES = 'BOARD_GAMES',
  GARDENING = 'GARDENING',
  LANGUAGES = 'LANGUAGES',
  FASHION = 'FASHION',
  TRIVIA = 'TRIVIA',
  MEDITATION = 'MEDITATION',
};

export const HobbyTypeDisplayName: Record<HobbyType, string> = {
  [HobbyType.SPORT]: 'Спорт',
  [HobbyType.TRAVEL]: 'Пътуване',
  [HobbyType.MUSIC]: 'Музика',
  [HobbyType.CINEMA]: 'Кино',
  [HobbyType.READING]: 'Четене',
  [HobbyType.COOKING]: 'Готвене',
  [HobbyType.DANCING]: 'Танци',
  [HobbyType.PHOTOGRAPHY]: 'Фотография',
  [HobbyType.GAMING]: 'Игри',
  [HobbyType.FITNESS]: 'Фитнес',
  [HobbyType.HIKING]: 'Планинарство',
  [HobbyType.TECHNOLOGY]: 'Технологии',
  [HobbyType.ART]: 'Изкуство',
  [HobbyType.THEATER]: 'Театър',
  [HobbyType.VOLUNTEERING]: 'Доброволчество',
  [HobbyType.YOGA]: 'Йога',
  [HobbyType.SWIMMING]: 'Плуване',
  [HobbyType.RUNNING]: 'Бягане',
  [HobbyType.CYCLING]: 'Колоездене',
  [HobbyType.BOARD_GAMES]: 'Настолни игри',
  [HobbyType.GARDENING]: 'Градинарство',
  [HobbyType.LANGUAGES]: 'Езици',
  [HobbyType.FASHION]: 'Мода',
  [HobbyType.TRIVIA]: 'Общи знания',
  [HobbyType.MEDITATION]: 'Медитация',
};